services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: ecommerce-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_PROD_USER}
      - POSTGRES_PASSWORD=${DB_PROD_PASS}
      - POSTGRES_DB=${DB_PROD_NAME}
    volumes:
      - pg_ecommerce_prod_data:/var/lib/postgresql/data

volumes:
  pg_ecommerce_prod_data: